services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'
            Symfony\Component\Messenger\MessageBusInterface $eventBus: '@event.bus'
            Symfony\Component\Messenger\MessageBusInterface $externalMessageBus: '@external_message.bus'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
